version: '3.8'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=your-secret-key
      - DB_PATH=/app/database/visitor.db
    volumes:
      - ./database:/app/database
    command: sh -c "npm rebuild sqlite3 && node dist/index.js"